language: bash
before_script:
  - git config --global user.email "travisci@example.com"
  - git config --global user.name "Travis CI Test"
  # Build changes in the repo
  - git checkout -b sourceBranch
  - touch file1.txt file2.txt
  - git add file1.txt
  - git commit -m "File 1"
  - git add file2.txt
  - git commit -m "File 2"
  # We use the current repo as remote repo
  - git remote add test .
script:
  # Show help
  - ./staging -h
  # Init the test repo with a remoteBranch from current master.
  - ./staging test remoteBranch origin/master
  # Push changes from sourceBranch to remote.
  - ./staging -v test remoteBranch sourceBranch
