language: bash
before_script:
  - git config --global user.email "travisci@example.com"
  - git config --global user.name "Travis CI Test"
  # Build changes in the repo
  - git checkout -b sourceBranch
  - touch file1.txt file2.txt
  - git add file1.txt
  - git commit -m "File 1"
  - git add file2.txt
  - git commit -m "File 2"
  # Create a remote repo to test with
  - mkdir test-repo
  - git --git-dir=./test-repo init --bare
  - git remote add test ./test-repo
script:
  # Init the test repo with a remoteBranch from current master.
  - bash staging.sh test remoteBranch master
  # Push changes from sourceBranch to remote.
  - bash staging.sh test remoteBranch sourceBranch
